#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Prompt theme
autoload -Uz promptinit
promptinit
prompt pure

# History search
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward

# zsh configure for tramp-mode
if [[ "$TERM" == "dumb" ]]; then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='$ '
fi

#
# Emacs
#

alias ew="emacsclient -c"
alias et="emacsclient -nw"
alias ekill="emacsclient -e '(kill-emacs)'"
alias edaemon="emacs --daemon"
alias eopen="emacsclient -n"

#
# Python
#

# pyenv configure
eval "$(pyenv init -)"

# pipenv dir configure
export PIPENV_VENV_IN_PROJECT=.

#
# Git
#
export GIT_PAGER=cat

#
# Utils
#

# Rename serial num
mvall() {
  NAME=$1
  EXT=$2
  awk '{printf "mv \"%s\" xxx%01d.yyy\n", $0, NR}' | sed "s/xxx/$(echo $NAME)/g" | sed "s/yyy/$(echo $EXT)/g"
}

# change AWS accounts
lsAWS() {
  cat ~/.aws/config | grep profile
}
showAWS() {
  echo Default account is \'$AWS_DEFAULT_PROFILE\'
  aws sts get-caller-identity
}
changeAWS() {
  export AWS_DEFAULT_PROFILE=$1
  echo Default account is changed \'$AWS_DEFAULT_PROFILE\'
}
alias clearAWS="unset AWS_DEFAULT_PROFILE"

# Convert Json -> YAML
json2yaml() {
  ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read))'
}

#
# DevTools on Docker
#

# python
dpython() {
  if [ -z $AWS_DEFAULT_PROFILE ]; then
    export AWS_DEFAULT_PROFILE='default'
  fi
  docker compose run --rm engine python ${@}
}
dpytest() {
  if [ -z $AWS_DEFAULT_PROFILE ]; then
    export AWS_DEFAULT_PROFILE='default'
  fi
  docker compose run --rm engine pytest ${@}
}

# sam
dsam(){
  if [ -z $AWS_DEFAULT_PROFILE ]; then
    export AWS_DEFAULT_PROFILE='default'
  fi
  docker compose run -v /var/run/docker.sock:/var/run/docker.sock --rm engine sam ${@}
}


#
# GCloud Tools
#

if [ -f "$(echo $HOME)/google-cloud-sdk/path.zsh.inc" ]; then . "$(echo $HOME)/google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$(echo $HOME)/google-cloud-sdk/completion.zsh.inc" ]; then . "$(echo $HOME)/google-cloud-sdk/completion.zsh.inc"; fi

#
# nvm
#

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

#
# goenv
#
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
eval "$(goenv init -)"
export PATH="$GOROOT/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"

#
# PostgreSQL
#
export PATH="/usr/local/opt/libpq/bin:$PATH"

#
# ghq + peco
#
bindkey "^]" peco-src
function peco-src () {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N peco-src

bindkey '^[' peco-git-checkout
function peco-git-checkout () {
    git fetch -p
    local selected_branch=$(git branch --list -a --no-color | grep remote | sed -e 's/remotes\/origin\///g' | colrm 1 2 | peco)
    echo ${selected_branch}
    if [ -n "$selected_branch" ]; then
    BUFFER="git checkout ${selected_branch}"
    zle accept-line
    fi
    zle clear-screen
}
zle -N peco-git-checkout