#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Prompt theme
autoload -Uz promptinit
promptinit
prompt pure

# History search
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward

# zsh configure for tramp-mode
if [[ "$TERM" == "dumb" ]]; then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='$ '
fi

#
# Emacs
#

alias ew="emacsclient -c"
alias et="emacsclient -nw"
alias ekill="emacsclient -e '(kill-emacs)'"
alias edaemon="emacs --daemon"

#
# Python
#

# pyenv configure
eval "$(pyenv init -)"

# pipenv dir configure
export PIPENV_VENV_IN_PROJECT=.


#
# Utils
#

# Rename serial num
mvall() {
  NAME=$1
  EXT=$2
  awk '{printf "mv \"%s\" xxx%01d.yyy\n", $0, NR}' | sed "s/xxx/$(echo $NAME)/g" | sed "s/yyy/$(echo $EXT)/g"
}

# change AWS accounts
lsAWS() {
  cat ~/.aws/config | grep profile
}
showAWS() {
  echo Default account is \'$AWS_DEFAULT_PROFILE\'
  aws sts get-caller-identity
}
changeAWS() {
  export AWS_DEFAULT_PROFILE=$1
  echo Default account is changed \'$AWS_DEFAULT_PROFILE\'
}
alias clearAWS="unset AWS_DEFAULT_PROFILE"

# Convert Json -> YAML
json2yaml() {
  ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read))'
}

#
# GCloud Tools
#

if [ -f "$(echo $HOME)/google-cloud-sdk/path.zsh.inc" ]; then . "$(echo $HOME)/google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$(echo $HOME)/google-cloud-sdk/completion.zsh.inc" ]; then . "$(echo $HOME)/google-cloud-sdk/completion.zsh.inc"; fi

#
# nvm
#

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
